### PR TITLE
Feature/add verify signature

### PR DESCRIPTION
**Pull request by majesticsomkid**
TXF2GQtDMtDQrgbHXkdvkXGVAqD6o1Sstm

### CODE REVIEW

**Comment by boughanmiadel** [comment]
Désabonnement 
 

Envoyé: mardi 13 avril 2021 à 19:23
De: "majesticsomkid" ***@***.***>
À: "tronprotocol/documentation" ***@***.***>
Cc: "Subscribed" ***@***.***>
Objet: [tronprotocol/documentation] Feature/add verify signature (#394)


TXF2GQtDMtDQrgbHXkdvkXGVAqD6o1Sstm


You can view, comment on, or merge this pull request online at:

  https://github.com/tronprotocol/documentation/pull/394

Commit Summary


	Merge pull request #343 from tronprotocol/feature/version_instruction
	Merge pull request #344 from tronprotocol/feature/version_instruction
	接口信息重复，redundant
	Update Official_Public_Node.md
	Update Official_Public_Node.md
	add mpc document initially
	split mpc document into several parts
	Update Official_Public_Node.md
	Update Official_Public_Node.md
	update read.me
	repair some expression error.
	Update 超级代表与委员会.md
	add verify_transform step of mpc.
	Update Official_Public_Node.md
	Update Official_Public_Node.md
	Update Official_Public_Node.md
	Update Official_Public_Node.md
	move mpc
	Update Tron-http.md
	Update README.md
	Merge pull request #368 from kevinLee2015/patch-3
	Merge remote-tracking branch 'pr1/patch-2'
	docs(CN/tron-http): fix #345, #350
	docs(README): deprecates this repo
	verify Signature


File Changes


	M README.md (20)
	M TRX/Official_Public_Node.md (52)
	M TRX_CN/Official_Public_Node.md (52)
	M TRX_CN/Tron-http.md (66)
	A 中文文档/二进制验证 .md (38)
	M 中文文档/波场协议/超级代表与委员会.md (3)
	A 中文文档/波场编程大赛/第一届波场编程大赛.md (129)


Patch Links:


	https://github.com/tronprotocol/documentation/pull/394.patch
	https://github.com/tronprotocol/documentation/pull/394.diff

**Comment by dkcam** [comment]
TQU2ZDqiSiWHWqkMryMaXtNjDbE2gavNpK

**Comment by dkcam** [comment]
TQU2ZDqiSiWHWqkMryMaXtNjDbE2gavNpK

**Comment by emadami** [comment]
https://github.com/tronprotocol/documentation/pull/394#issue-614635312

**Comment by Benson0224** [comment]
This PR is out of date, will be closed. 
Please submit new PR with correct changes. thanks.

**Comment by mahmod87** [comment]
[TXF2GQtDMtDQrgbHXkdvkXGVAqD6o1Sstm](https://github.com/tronprotocol/documentation/pull/394)

**Pull request closed without merging**
