### PR TITLE
Update Official_Public_Node.md

### PR DESCRIPTION
**Pull request by vivian1912**

### CODE REVIEW

**Review by ethan1844 — APPROVED** [review]

**Review by Ahmed7683 — COMMENTED** [review]
G

**Review by Ahmed7683 — COMMENTED** [review]
F

**Review by AnwarSalam72 — APPROVED** [review]
Ok

**Review by nimoona692 — APPROVED** [review]

**Review by Queenbih87 — APPROVED** [review]
Reviewed

**Comment by srbaeza-ai** [comment]
Great 👍

**Review by AnwarSalam72 — APPROVED** [review]

**Pull request merged**
